import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import Navbar from "../components/navbar/navbar";
import Carrousel from "../components/headfoot/Carrousel";
import Footer from "../components/headfoot/footer";
import Body from "./main/body";
import Map from "../components/maps/mapa";
//import Weather from "../pages/weather/weather";
import { useEffect } from "react";
import { main } from "@popperjs/core";
import LastNew from "./news/LastNew";
import LastVideo from "./videos/Lastvideo";



const mapStyles = {
  marginTop:'125px',
	height: '450px'

  };




export default function Home() {
  // useEffect(async () => {
  //   await fetch("http://appmurcia_codeigniter.test/rest/weather")
  //     .then((response) => response.json())
  //     .then((data) => console.log(data));
  // });
  return (
    <>
      <div className="head">
        <Head>
          <title>Murcia Turismo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className="mainfer">
        <Navbar />
      </div>
      <div className="container mt-4">
        <Carrousel />
      </div>
      {/* <div className="container mt-4">
        <Weather />
      </div> */}
      <div className="container mt-4"></div>
      <div className="container mt-4">
        <h2 style={{ textAlign: "center" }}>
          Murcia destino de calidad, destino seguro
        </h2>
        <p style={{ textAlign: "center" }}>
          Ven y disfruta de su fantástico patrimonio cultural e histórico, de su
          reconocida gastronomía, de su naturaleza y <br></br>
          de su gran oferta de ocio. Descubre una ciudad viva, dinámica,
          emprendedora y con un clima envidiable durante <br></br>
          todo el año.
        </p>
        <h4 style={{ textAlign: "center" }}>Seguro que Murcia es para ti</h4>
      </div>

      <div className="mx-auto">
        <div style={mapStyles}>
          <Map />
          </div>
      </div>
      <div class="container mt-5 mb-5">
        <Body/>
      </div> 
      <div class="container mt-5 mb-5">
        <LastNew/>
      </div> 
      <div class="container mt-5 mb-5" >
        {/*<LastVideo/>*/}
        <Link href="./videos/Lastvideo">
          <a>Video</a>
        </Link>
      </div> 


      <div
        class="footer mt-5"
        style={{
          position: "fixed !important",
          width: "100% !important",
          bottom: "0 !important",
        }}
      >
        <Footer />
      </div>
    </>
  );
}


