import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import Navbar from '../components/navbar/navbar'
import Carrousel from '../components/headfoot/Carrousel'
import Footer from '../components/headfoot/footer'
import Body from './main/body'

export default function Home() {
  return (
    <>
      <div className="head">
        <Head>
          <title>Murcia Turismo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className='mainfer'>
        <Navbar/>
      </div>
      <div className='container mt-4'>
        <Carrousel/>
      </div>
      <div class="conatiner mt-5 mb-5">
        <Body/>
      </div>
      <div class="footer mt-5">
        <Footer/>
      </div>

     
    
    
    
    </>
  )
}
  